version: '3.8'

services:
  nginx:
    image: nginx

    container_name: nginx

    ports:
      - "81:80"

    volumes:
      - ./site:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      
    networks:
      - docker-network

  php:
    image: php:fpm

    container_name: php

    volumes:
      - ./site:/usr/share/nginx/html

    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
